version: '3'
services:
  web:
    build: .
    ports:
      - "4040:4040"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 4040
